import type { ModelInfo } from "../model.js"

export type GptChatByModelId = keyof typeof gptChatByModels

export const gptChatByDefaultModelId: GptChatByModelId = "coder-flash"

const GTP_CHAT_BY_TAKE_PROFIT_USD = 1.15;

export const gptChatByModels = {
	"mimo-free": {
		maxTokens: 65_000,
		contextWindow: 150_000,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 0,
		outputPrice: 0,
		description: `Mimo v2 Flash.`,
		isFree: true,
	},
	"kat-coder-free": {
		maxTokens: 32_000,
		contextWindow: 150_000,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 0,
		outputPrice: 0,
		description: `Mimo v2 Flash.`,
		isFree: true,
	},
	"openai-free": {
		maxTokens: 8000,
		contextWindow: 65_000,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 0,
		outputPrice: 0,
		description: `Open AI GPT-5 nano`,
		isFree: true,
	},
	"coder": {
		maxTokens: 65_000,
		contextWindow: 1_000_000,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: GTP_CHAT_BY_TAKE_PROFIT_USD,
		outputPrice: 5 * GTP_CHAT_BY_TAKE_PROFIT_USD,
		description: `Coder - High-performance coding model with 1M context window for large codebases.`,
	},
	"coder-flash": {
		maxTokens: 65_000,
		contextWindow: 1_000_000,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 0.3 * GTP_CHAT_BY_TAKE_PROFIT_USD, // $0.28 per million tokens (cache miss) - Updated Oct 29, 2025
		outputPrice: 1.5 * GTP_CHAT_BY_TAKE_PROFIT_USD, // $0.42 per million tokens - Updated Oct 29, 2025
		description: `Coder Flash - Fast coding model with 1M context window optimized for speed.`,
	},
	"gemini-3-flash": {
		maxTokens: 65_000,
		contextWindow: 1_000_000,
		supportsImages: false,
		supportsPromptCache: false,
		inputPrice: 0.5 * GTP_CHAT_BY_TAKE_PROFIT_USD,
		outputPrice: 3 * GTP_CHAT_BY_TAKE_PROFIT_USD,
		description: `Google: Gemini 3 Flash Preview.`,
	},
	"deepseek/deepseek-v3.2": {
		maxTokens: 65_000,
		contextWindow: 160_000,
		supportsImages: false,
		supportsPromptCache: false,
		inputPrice: 0.28 * GTP_CHAT_BY_TAKE_PROFIT_USD,
		outputPrice: 0.45 * GTP_CHAT_BY_TAKE_PROFIT_USD,
		description: `deepseek 3.2`,
	},
	"minimax/m2.1": {
		maxTokens: 120_000,
		contextWindow: 180_000,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 0.12 * GTP_CHAT_BY_TAKE_PROFIT_USD,
		outputPrice: 0.48 * GTP_CHAT_BY_TAKE_PROFIT_USD,
		description: `MiniMax M2.1`,
	},
	"minimax/m2": {
		maxTokens: 65_000,
		contextWindow: 180_000,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 0.2 * GTP_CHAT_BY_TAKE_PROFIT_USD,
		outputPrice: GTP_CHAT_BY_TAKE_PROFIT_USD,
		description: `MiniMax M2`,
	},
	"x/grok-code": {
		maxTokens: 65_000,
		contextWindow: 1_000_000,
		supportsImages: false,
		supportsPromptCache: false,
		inputPrice: 0.2 * GTP_CHAT_BY_TAKE_PROFIT_USD,
		outputPrice: 1.5 * GTP_CHAT_BY_TAKE_PROFIT_USD,
		description: `Google: Gemini 3 Flash Preview.`,
	},
	"anthropic/claude-opus-4.5": {
		maxTokens: 64_000,
		contextWindow: 200_000,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 5 * GTP_CHAT_BY_TAKE_PROFIT_USD,
		outputPrice: 25 * GTP_CHAT_BY_TAKE_PROFIT_USD,
		description: `Google: Gemini 3 Flash Preview.`,
	},
	"anthropic/claude-sonnet-4.5": {
		maxTokens: 64_000,
		contextWindow: 1_000_000,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 3 * GTP_CHAT_BY_TAKE_PROFIT_USD,
		outputPrice: 15 * GTP_CHAT_BY_TAKE_PROFIT_USD,
		description: `Google: Gemini 3 Flash Preview.`,
	},
	"openai/gpt-5-codex": {
		maxTokens: 65_000,
		contextWindow: 1_000_000,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 1.25 * GTP_CHAT_BY_TAKE_PROFIT_USD,
		outputPrice: 10 * GTP_CHAT_BY_TAKE_PROFIT_USD,
		description: `Open AI gpt 5`,
	},
	"openai/gpt-5.1": {
		maxTokens: 65_000,
		contextWindow: 1_000_000,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 1.25 * GTP_CHAT_BY_TAKE_PROFIT_USD,
		outputPrice: 10 * GTP_CHAT_BY_TAKE_PROFIT_USD,
		description: `Open AI gpt 5.1`,
	},
	"openai/gpt-5.2": {
		maxTokens: 128_000,
		contextWindow: 400_000,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 1.75 * GTP_CHAT_BY_TAKE_PROFIT_USD,
		outputPrice: 14 * GTP_CHAT_BY_TAKE_PROFIT_USD,
		description: `Open AI gpt 5.2`,
	},
} as const satisfies Record<string, ModelInfo>

export const GPT_CHAT_BY_DEFAULT_TEMPERATURE = 0.6
